# mvn exec:java -Dexec.mainClass=research.diffsearch.main.App -Dexec.args="-r -oj -q \"ID<1>(ID<2>, LT<3>);-->ID<1>(LT<3>, ID<2>);\""
# mvn exec:java -Dexec.mainClass=research.diffsearch.main.App -Dexec.args="-oj -r -q \"EXPR = ID<1>(<...>);-->EXPR = ID<1>(<...>);\""
mvn exec:java -Dexec.mainClass=research.diffsearch.main.App -Dexec.args="-oj -q \"ID<0>.ID<1>(ID, LT)-->ID<0>.ID<1>(ID, LT)\""
mvn exec:java -Dexec.mainClass=research.diffsearch.main.App -Dexec.args="-oj -q \"LT-->LT binOP LT\""
mvn exec:java -Dexec.mainClass=research.diffsearch.main.App -Dexec.args="-oj -r -q \"return;-->return ID;\""
mvn exec:java -Dexec.mainClass=research.diffsearch.main.App -Dexec.args="-oj -q \"System.out.println(EXPR);-->_\""
# mvn exec:java -Dexec.mainClass=research.diffsearch.main.App -Dexec.args="-oj -r -q \"ID<0> * ID<1>;-->ID<0> + ID<1>;\""
# mvn exec:java -Dexec.mainClass=research.diffsearch.main.App -Dexec.args="-oj -r -q \"EXPR = LT;-->EXPR = ID;\""
mvn exec:java -Dexec.mainClass=research.diffsearch.main.App -Dexec.args="-oj -q \"_-->import java.io.ID;\""
# mvn exec:java -Dexec.mainClass=research.diffsearch.main.App -Dexec.args="-oj -r -q \"if (EXPR != null) {-->if (EXPR == null) {\""
mvn exec:java -Dexec.mainClass=research.diffsearch.main.App -Dexec.args="-oj -q \"EXPR-->try {EXPR;} catch (ID ID) {<...>}\""
# mvn exec:java -Dexec.mainClass=research.diffsearch.main.App -Dexec.args="-oj -r -q \"EXPR = ID + LT;-->EXPR = LT + ID;\""
mvn exec:java -Dexec.mainClass=research.diffsearch.main.App -Dexec.args="-oj -q \"EXPR.ID<0>(); --> EXPR.ID<0>();\""
mvn exec:java -Dexec.mainClass=research.diffsearch.main.App -Dexec.args="-oj -q \"EXPR.ID<0>(EXPR<0>); --> EXPR.ID<0>(EXPR<0>);\""
mvn exec:java -Dexec.mainClass=research.diffsearch.main.App -Dexec.args="-oj -q \"EXPR.ID<0>(EXPR<0>, EXPR<1>); --> EXPR.ID<0>(EXPR<0>, EXPR<1>);\""
mvn exec:java -Dexec.mainClass=research.diffsearch.main.App -Dexec.args="-oj -q \"EXPR.ID<0>(EXPR<0>, EXPR<1>,EXPR<2>, EXPR<3>); --> EXPR.ID<0>(EXPR<0>, EXPR<1>, EXPR<2>, EXPR<2>);\""
mvn exec:java -Dexec.mainClass=research.diffsearch.main.App -Dexec.args="-oj -q \"<...> ID(<...>) throws ID { --> <...> ID(<...>) {\""
# mvn exec:java -Dexec.mainClass=research.diffsearch.main.App -Dexec.args="-oj -r -q \"ID<1>.ID<0>(<...>) unOP --> ID<1>.ID<0>(<...>) unOP\""
mvn exec:java -Dexec.mainClass=research.diffsearch.main.App -Dexec.args="-oj -q \"ID<0>() --> ID<0>(EXPR)\""
# mvn exec:java -Dexec.mainClass=research.diffsearch.main.App -Dexec.args="-oj -r -q \"if (ID<0>) {--> if (EXPR || ID<0>) {\""